### PR TITLE
package.json: fixed yarn warnings

### PR DESCRIPTION
**Pull request by eragon512**
In response to issue #2

Screenshots: 

screen shot 2018-10-11 at 7 18 30 pm
screen shot 2018-10-11 at 7 18 43 pm

### CODE REVIEW

**Comment by mykeels** [comment]
Hey @eragon512 ... Thanks for working on this.

I realise I hadn't pushed the commit that uses `yarn.lock` rather than a `package-lock.json` file.

Could you please pull the master again and implement the update?

**Comment by eragon512** [comment]
hey @mykeels , check the PR, I implemented the update

**Comment by mykeels** [comment]
Thanks @eragon512

**Comment by eragon512** [comment]
:+1:

**Pull request merged**
